// for category
export const GET_CATEGORIES_BEGIN = 'GET_CATEGORIES_BEGIN';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const GET_SINGLE_CATEGORY_BEGIN = 'GET_SINGLE_CATEGORY_BEGIN';
export const GET_SINGLE_CATEGORY_SUCCESS = 'GET_SINGLE_CATEGORY_SUCCESS';
export const GET_SINGLE_CATEGORY_ERROR = 'GET_SINGLE_CATEGORY_ERROR';
// for games
export const GET_GAMES_BEGIN = 'GET_GAMES_BEGIN';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_GAMES_BY_CATEGORY_BEGIN = 'GET_GAMES_BY_CATEGORY_BEGIN';
export const GET_GAMES_BY_CATEGORY_SUCCESS = 'GET_GAMES_BY_CATEGORY_SUCCESS';
export const GET_GAMES_BY_CATEGORY_ERROR = 'GET_GAMES_BY_CATEGORY_ERROR';
export const GET_SINGLE_GAME_BEGIN = 'GET_SINGLE_GAME_BEGIN';
export const GET_SINGLE_GAME_SUCCESS = 'GET_SINGLE_GAME_SUCCESS';
export const GET_SINGLE_GAME_ERROR = 'GET_SINGLE_GAME_ERROR';
export const GET_REVIEWS_BY_GAME_BEGIN = 'GET_REVIEWS_BY_GAME_BEGIN';
export const GET_REVIEWS_BY_GAME_SUCCESS = 'GET_REVIEWS_BY_GAME_SUCCESS';
export const GET_REVIEWS_BY_GAME_ERROR = 'GET_REVIEWS_BY_GAME_ERROR';
// for gears
export const GET_GEARS_BEGIN = 'GET_GEARS_BEGIN';
export const GET_GEARS_SUCCESS = 'GET_GEARS_SUCCESS';
export const GET_GEARS_ERROR = 'GET_GEARS_ERROR';
export const GET_SINGLE_GEAR_BEGIN = 'GET_SINGLE_GEAR_BEGIN';
export const GET_SINGLE_GEAR_SUCCESS = 'GET_SINGLE_GAME_SUCCESS';
export const GET_SINGLE_GEAR_ERROR = 'GET_SINGLE_GEAR_ERROR';
// for games filter
export const LOAD_GAMES = 'LOAD_GAMES';
export const SET_GRIDVIEW = 'SET_GRIDVIEW';
export const SET_LISTVIEW = 'SET_LISTVIEW';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SORT_GAMES = 'SORT_GAMES';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_GAMES = 'FILTER_GAMES';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
// for cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_CART_TOTAL = 'COUNT_CART_TOTAL';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
// for gears filter
export const LOAD_GEARS = 'LOAD_GEARS';
export const SET_GEARS_GRIDVIEW = 'SET_GEARS_GRIDVIEW';
export const SET_GEARS_LISTVIEW = 'SET_GEARS_LISTVIEW';
export const UPDATE_GEARS_SORT = 'UPDATE_GEARS_SORT';
export const SORT_GEARS = 'SORT_GEARS';
export const UPDATE_GEARS_FILTERS = 'UPDATE_GEARS_FILTERS';
export const FILTER_GEARS = 'FILTER_GEARS';
export const CLEAR_GEARS_FILTERS = 'CLEAR_GEARS_FILTERS';
// for authentication
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
